/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_ChangeVoiceActivity */

#include <fmod.hpp>

#ifndef _Included_com_example_ndk_ChangeVoiceActivity
#define _Included_com_example_ndk_ChangeVoiceActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ndk_ChangeVoiceActivity_MODE_NORMAL
#define com_example_ndk_ChangeVoiceActivity_MODE_NORMAL 0L
#undef com_example_ndk_ChangeVoiceActivity_MODE_LUOLI
#define com_example_ndk_ChangeVoiceActivity_MODE_LUOLI 1L
#undef com_example_ndk_ChangeVoiceActivity_MODE_DASHU
#define com_example_ndk_ChangeVoiceActivity_MODE_DASHU 2L
#undef com_example_ndk_ChangeVoiceActivity_MODE_JINGSONG
#define com_example_ndk_ChangeVoiceActivity_MODE_JINGSONG 3L
#undef com_example_ndk_ChangeVoiceActivity_MODE_GAOGUAI
#define com_example_ndk_ChangeVoiceActivity_MODE_GAOGUAI 4L
#undef com_example_ndk_ChangeVoiceActivity_MODE_KONGLING
#define com_example_ndk_ChangeVoiceActivity_MODE_KONGLING 5L
/*
 * Class:     com_example_ndk_ChangeVoiceActivity
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_example_ndk_ChangeVoiceActivity_voiceChangeNative
(JNIEnv*, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
