/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_example_ndk_MainActivity */
//解决循环COpy的问题 第二次就进不来了
#ifndef _Included_com_example_ndk_MainActivity
#define _Included_com_example_ndk_MainActivity
#ifdef __cplusplus //如果是C++环境
extern "C" {//全部采用C的方式 禁止函数重载
#endif
#undef com_example_ndk_MainActivity_A
#define com_example_ndk_MainActivity_A 12L
/*
 * Class:     com_example_ndk_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    getStringPWD
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_MainActivity_getStringPWD
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
